import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-gray-700">
        <div className="lg:hidden">{children}</div>
        <div className="h-screen flex items-center justify-center">
          <p className="text-xl font-medium">You must be in mobile device or size to use this page</p>
        </div>
      </body>
    </html>
  );
}
